<a href="https://colab.research.google.com/github/yuvashri-Y/ML/blob/main/Gradient_boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

In [ ]:
test=pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Titanic/test.csv")
train=pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Titanic/train.csv")

In [ ]:
train.info(),test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

(None, None)

In [ ]:
train.set_index("PassengerId",inplace=True)
test.set_index("PassengerId",inplace=True)

In [ ]:
y_train=train["Survived"]

In [ ]:
train

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
train.drop(labels="Survived", axis=1, inplace=True)

In [ ]:
train.shape

(891, 10)

In [ ]:
train_test=train.append(test)

<ipython-input-22-d2734cde2921>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_test=train.append(test)

In [ ]:
columns_to_drop=['Name','Age','SibSp','Ticket','Cabin','Parch','Embarked']
train_test.drop(labels=columns_to_drop, axis=1, inplace=True)

In [ ]:
train_test

             Pclass     Sex      Fare
PassengerId
1                 3    male    7.2500
2                 1  female   71.2833
3                 3  female    7.9250
4                 1  female   53.1000
5                 3    male    8.0500
...             ...     ...       ...
1305              3    male    8.0500
1306              1  female  108.9000
1307              3    male    7.2500
1308              3    male    8.0500
1309              3    male   22.3583

[1309 rows x 3 columns]

In [ ]:
train_test_dummies=pd.get_dummies(train_test,columns=['Sex'])

In [ ]:
train_test_dummies.shape

(1309, 4)

In [ ]:
train_test_dummies.isnull().sum()

Pclass        0
Fare          1
Sex_female    0
Sex_male      0
dtype: int64

In [ ]:
train_test_dummies.fillna(value=0.0, inplace=True)

In [ ]:
x_train=train_test_dummies.values[0:891]
x_test=train_test_dummies.values[891:]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train_scale=scaler.fit_transform(x_train)
x_test_scale=scaler.transform(x_test)

In [ ]:
from sklearn.model_selection import train_test_split
x_train_sub,x_validation_sub,y_train_sub,y_validation_sub=train_test_split(x_train_scale,y_train,random_state=0)

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
learning_rate=[0.05,0,1,0.25,0.5,0.75,1]
for learning_rate in learning_rate:
  gb=GradientBoostingClassifier(n_estimators=20,learning_rate=learning_rate,max_features=2,max_depth=2,random_state=0)
  gb.fit(x_train_sub,y_train_sub)
  print("Learning_rate:",learning_rate)
  print("Accuracy score (training):{0:.3f}".format(gb.score(x_train_sub,y_train_sub)))
  print("Accuracy score (validation):{0:.3f}".format(gb.score(x_validation_sub,y_validation_sub)))

Learning_rate: 0.05
Accuracy score (training):0.789
Accuracy score (validation):0.780
Learning_rate: 0
Accuracy score (training):0.614
Accuracy score (validation):0.623
Learning_rate: 1
Accuracy score (training):0.831
Accuracy score (validation):0.789
Learning_rate: 0.25
Accuracy score (training):0.816
Accuracy score (validation):0.803
Learning_rate: 0.5
Accuracy score (training):0.826
Accuracy score (validation):0.834
Learning_rate: 0.75
Accuracy score (training):0.831
Accuracy score (validation):0.789
Learning_rate: 1
Accuracy score (training):0.831
Accuracy score (validation):0.789